name: MidensBounties
main: net.cozycosmos.midensbounties.MidensBounties
author: Miden
version: 1.1.1
depend: [Vault]
softdepend: [PlaceHolderAPI]

commands:
  bounty:
    description: Check your own bounty
    permission: midensbounties.bounty
    usage: Use /bounty to check your own bounty
  setbounty:
    description: Put a bounty on someone else's head
    permission: midensbounties.setbounty
    usage: use /setbounty [name] [amount] to put a bounty on someone's head

permissions:
  midensbounties.bounty:
    description: Gives access to the /bounty command
    default: true
  midensbounties.setbounty:
    description: Gives access to the /setbounty command
    default: true
